### ISSUE TITLE
Update nuget to new version

### ISSUE THREAD

**Issue by TomMalow** [delegateas/XrmFramework#11]
The framework currently uses a very old version nuget, 2.8. A simple upgrade does not seem to be possible as [the new version breaks some pathing](https://github.com/NuGet/Home/issues/7657). There is a workaround found [here](https://github.com/NuGet/Home/issues/7657#issuecomment-450954226) but unsure if it is sustainable.

**Comment by misoeli** [comment]
Closed by #16 .
