### ISSUE TITLE
Error when running XrmContext.exe

### ISSUE THREAD

**Issue by robertraaijmakers** [delegateas/XrmFramework#13]
Hi There,

I'm receiving the following error when generating the context.

Fetching specific entity metadata from CRM...Done!
Retrieving CRM version...Done!
Interpreting data...
**Unable to generate context files: One or more errors occurred.**

The strange thing is, that the error occurs when I run it on the dev environment, but doesn't occur when I run it on the test environment. Is there some way to enable debugging to see where it goes wrong?

**Comment by magesoe** [comment]
You can run the EXE directly. It is located in the Tools project. Then it should give you something meaningful.

**Comment by robertraaijmakers** [comment]
I think I'm running the exe directly (through the command line, because if I run the .exe, it shuts down immediately after showing the message).

So I'm running the .exe below... Or is there another executable?
![image](https://user-images.githubusercontent.com/1773099/100460705-ec89a180-30c7-11eb-8681-1e736517be3c.png)

**Comment by magesoe** [comment]
Then you are running it directly. Can you show the config and args you run it with?

**Comment by robertraaijmakers** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="url" value="https://<<url>>.crm4.dynamics.com/XRMServices/2011/Organization.svc" />
    <add key="username" value="<<myemail>>" />
    <add key="password" value="<<mypassword>>" />
    <add key="out" value="..\..\<<customer>>.Dynamics365.Plugins.Shared\Models\" />
    <add key="entities" value="account, contact, team, systemuser, opportunity, << some more entities >>" />
    <add key="ns" value="<<customername>>.Dynamics365.Plugins.Shared.Models"/>
  </appSettings>
</configuration>

Just running it via CMD with XrmContext.exe

Thanks for your time!

**Comment by magesoe** [comment]
Nothing stands out, are you using the latest version?

**Comment by robertraaijmakers** [comment]
Yes, 1.8 from the top of my head. Been using the tool for almost 1.5 year on this project without any issues. But something has changed (probably in our environment) that is causing some issues (maybe parsing issues?). Some new data type that isn't supported or something? Thats why I was wondering if there is a way to get some extra debugging information from the tool somehow.

**Comment by robertraaijmakers** [comment]
Is there a way to run the tool in debugging mode (download the project and link visual studio debugger)? Tried all kind of solutions but couldn't get some extra debug information from the tool and can't figure out what has changed on our development environment since last week.

**Comment by magesoe** [comment]
You can download the tool from here and set your configurations in the app.config and then run the project from visual studio

**Comment by robertraaijmakers** [comment]
Logged a new issue in the correct repository with a pull request that should solve the nullreference exception :)
