### ISSUE TITLE
ILMerge

### ISSUE THREAD

**Issue by altmank** [delegateas/XrmFramework#3]
This project uses an ILMerge step after build of the plugin project. I was reading that ILMerge is not supported (but still usable) for D365 online. Is this correct that ILMerge is not supported and if so, do you have any alternate project structure updates planned to bypass the usage of ILMerge?

**Comment by magesoe** [comment]
Yes, you can make the depending projects Shared Code Projects. So in this base skeleton you can make business logic and business domain shared code projects and include them in your plugins and workflow projects

**Comment by altmank** [comment]
Awesome, thanks for clarifying.
