### ISSUE TITLE
Updating assembly version is not reflected in merged assemblies

### ISSUE THREAD

**Issue by TomMalow** [delegateas/XrmFramework#4]
Updating the assembly version in either the plugin project or the workflow project is not reflected in the merged assembly. 

This probably happened with the shift to ILRepack tool instead if ILmerge. When using ILRepack the assembly version needs to be specified in the command call or else it defaults to version 1.0.0.0

**Comment by magesoe** [comment]
The version is taken from the first assembly specified in the repack. Tested this morning

**Comment by TomMalow** [comment]
Great! Have to test that

**Comment by TomMalow** [comment]
That solves it! The plugin/workflow assembly is specified last. Changing it to be the first fixes the issue.
